import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# FairMobility: Graph Neural Network (GNN) PPO Training\n",
    "Questo notebook implementa una Graph Convolutional Network (GCN) in puro PyTorch all'interno di un estrattore di feature custom per Stable Baselines 3. L'Intelligenza Artificiale impara la fluidodinamica passando messaggi tra i 100 nodi della citta' senza bisogno di installare torch_geometric!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "!pip install stable-baselines3[extra] pandas scipy numpy shimmy>=2.0 gymnasium"
   ],
   "outputs": []
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "import gymnasium as gym\n",
    "from gymnasium import spaces\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from scipy.spatial import Delaunay\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "from stable_baselines3 import PPO\n",
    "from stable_baselines3.common.torch_layers import BaseFeaturesExtractor\n",
    "\n",
    "print('Librerie caricate con successo!')"
   ],
   "outputs": []
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "df = pd.read_csv('smart_city_traffic_mobility.csv')\n",
    "hourly_agg = df.groupby(['latitude', 'longitude', 'hour']).agg({\n",
    "    'emission_estimate': 'mean',\n",
    "    'heavy_vehicle_count': 'mean',\n",
    "    'nearby_school': 'max',\n",
    "    'nearby_hospital': 'max',\n",
    "    'average_wait_time': 'mean',\n",
    "    'vehicle_count': 'mean',\n",
    "    'public_transport_count': 'mean',\n",
    "    'lanes': 'first'\n",
    "}).reset_index()\n",
    "\n",
    "# Costruzione del Grafo Planare (Delaunay)\n",
    "coords = hourly_agg[hourly_agg['hour'] == 8][['latitude', 'longitude']].values\n",
    "tri = Delaunay(coords)\n",
    "num_nodes = len(coords)\n",
    "adj = np.zeros((num_nodes, num_nodes), dtype=np.float32)\n",
    "\n",
    "for simplex in tri.simplices:\n",
    "    for i in range(3):\n",
    "        for j in range(i+1, 3):\n",
    "            u, v = simplex[i], simplex[j]\n",
    "            adj[u, v] = 1.0\n",
    "            adj[v, u] = 1.0\n",
    "\n",
    "# Normalizzazione GCN: A_tilde = D^(-1/2) * (A + I) * D^(-1/2)\n",
    "adj_tilde = adj + np.eye(num_nodes)\n",
    "deg = np.sum(adj_tilde, axis=1)\n",
    "deg_inv_sqrt = np.power(deg, -0.5)\n",
    "deg_inv_sqrt[np.isinf(deg_inv_sqrt)] = 0.0\n",
    "D_inv_sqrt = np.diag(deg_inv_sqrt)\n",
    "norm_adj = np.dot(np.dot(D_inv_sqrt, adj_tilde), D_inv_sqrt)\n",
    "\n",
    "# Salviamo la matrice norm_adj come tensore PyTorch globale\n",
    "global_norm_adj = torch.FloatTensor(norm_adj)\n",
    "print('Grafo di Delaunay Costruito e Normalizzato per GCN!')"
   ],
   "outputs": []
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "class PurePyTorchGCNExtractor(BaseFeaturesExtractor):\n",
    "    def __init__(self, observation_space: gym.Space, features_dim: int = 64):\n",
    "        super(PurePyTorchGCNExtractor, self).__init__(observation_space, features_dim)\n",
    "        self.node_features = 12\n",
    "        self.num_nodes = observation_space.shape[0] // self.node_features\n",
    "        \n",
    "        # Layer GCN 1\n",
    "        self.weight1 = nn.Parameter(torch.FloatTensor(self.node_features, 32))\n",
    "        self.bias1 = nn.Parameter(torch.FloatTensor(32))\n",
    "        \n",
    "        # Layer GCN 2\n",
    "        self.weight2 = nn.Parameter(torch.FloatTensor(32, 64))\n",
    "        self.bias2 = nn.Parameter(torch.FloatTensor(64))\n",
    "        \n",
    "        # Inizializzazione pesi Xavier\n",
    "        nn.init.xavier_uniform_(self.weight1)\n",
    "        nn.init.zeros_(self.bias1)\n",
    "        nn.init.xavier_uniform_(self.weight2)\n",
    "        nn.init.zeros_(self.bias2)\n",
    "\n",
    "    def forward(self, observations: torch.Tensor) -> torch.Tensor:\n",
    "        # observations ha shape [batch_size, 1200]\n",
    "        batch_size = observations.size(0)\n",
    "        # Reshape in [batch_size, 100 nodi, 12 features]\n",
    "        x = observations.view(batch_size, self.num_nodes, self.node_features)\n",
    "        \n",
    "        adj = global_norm_adj.to(observations.device)\n",
    "        \n",
    "        # Message Passing 1: A * X * W1\n",
    "        ax = torch.matmul(adj, x) \n",
    "        out1 = F.relu(torch.matmul(ax, self.weight1) + self.bias1)\n",
    "        \n",
    "        # Message Passing 2: A * H1 * W2\n",
    "        ax2 = torch.matmul(adj, out1)\n",
    "        out2 = F.relu(torch.matmul(ax2, self.weight2) + self.bias2)\n",
    "        \n",
    "        # Global Mean Pooling (aggrega i 100 nodi in un unico vettore da 64 per il PPO)\n",
    "        graph_embedding = torch.mean(out2, dim=1)\n",
    "        return graph_embedding\n",
    "print('Architettura GNN (Custom Feature Extractor) pronta per PPO!')"
   ],
   "outputs": []
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "class GraphCityEnv(gym.Env):\n",
    "    def __init__(self, full_df, adj_matrix):\n",
    "        super(GraphCityEnv, self).__init__()\n",
    "        self.full_df = full_df\n",
    "        self.adj_matrix = adj_matrix\n",
    "        self.timestamps = self.full_df['hour'].unique()\n",
    "        self.num_nodes = len(adj_matrix)\n",
    "        \n",
    "        # Spazio Azione: [Env, Modal, Spatial]\n",
    "        self.action_space = spaces.Box(low=0.0, high=1.0, shape=(3,), dtype=np.float32)\n",
    "        \n",
    "        # Spazio Osservazione: num_nodes x 12 features\n",
    "        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(self.num_nodes * 12,), dtype=np.float32)\n",
    "        \n",
    "    def reset(self, seed=None, options=None):\n",
    "        super().reset(seed=seed)\n",
    "        self.current_ts = np.random.choice(self.timestamps)\n",
    "        self.current_df = self.full_df[self.full_df['hour'] == self.current_ts].copy().reset_index(drop=True)\n",
    "        if len(self.current_df) != self.num_nodes:\n",
    "            raise ValueError(f'Mismatch: current_df has {len(self.current_df)} rows, expected {self.num_nodes}.')\n",
    "        return self._get_obs(), {}\n",
    "        \n",
    "    def _get_obs(self):\n",
    "        features = []\n",
    "        for i in range(self.num_nodes):\n",
    "            veh = self.current_df.at[i, 'vehicle_count'] / 1000.0\n",
    "            hvy = self.current_df.at[i, 'heavy_vehicle_count'] / 100.0\n",
    "            bus = self.current_df.at[i, 'public_transport_count'] / 50.0\n",
    "            emg = 1.0 if self.current_df.at[i, 'emergency_vehicle_detected'] == 'Yes' else 0.0\n",
    "            lanes = self.current_df.at[i, 'lanes'] / 4.0\n",
    "            spd = self.current_df.at[i, 'speed_limit'] / 100.0\n",
    "            school = 1.0 if self.current_df.at[i, 'nearby_school']==1 else 0.0\n",
    "            hosp = 1.0 if self.current_df.at[i, 'nearby_hospital']==1 else 0.0\n",
    "            acc = 1.0 if self.current_df.at[i, 'accident_reported'] == 'Yes' else 0.0\n",
    "            emi = self.current_df.at[i, 'emission_estimate'] / 1000.0\n",
    "            wait = self.current_df.at[i, 'average_wait_time'] / 100.0\n",
    "            queue = self.current_df.at[i, 'queue_length'] / 500.0\n",
    "            features.extend([veh, hvy, bus, emg, lanes, spd, school, hosp, acc, emi, wait, queue])\n",
    "        return np.array(features, dtype=np.float32)\n",
    "\n",
    "    def step(self, action):\n",
    "        # Simulazione dummy veloce per allenare la rete nel notebook\n",
    "        df = self.current_df.copy()\n",
    "        # Calcolo di metriche fittizie dipendenti dall'azione per test\n",
    "        penalty = sum([abs(a - 0.5) for a in action])\n",
    "        reward = -float(penalty)\n",
    "        # In Gymnasium step ritorna 5 valori: obs, reward, terminated, truncated, info\n",
    "        return self._get_obs(), reward, True, False, {}\n",
    "\n",
    "# ---------------------\n",
    "# INIZIO TRAINING\n",
    "# ---------------------\n",
    "env = GraphCityEnv(hourly_agg, adj)\n",
    "\n",
    "policy_kwargs = dict(\n",
    "    features_extractor_class=PurePyTorchGCNExtractor,\n",
    "    features_extractor_kwargs=dict(features_dim=64),\n",
    ")\n",
    "\n",
    "model = PPO('MlpPolicy', env, policy_kwargs=policy_kwargs, verbose=1, learning_rate=0.0003)\n",
    "\n",
    "print('Inizio addestramento GNN (test)...')\n",
    "model.learn(total_timesteps=2048)\n",
    "model.save('gnn_fair_city_model')\n",
    "print('Modello GNN salvato con successo!')"
   ],
   "outputs": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open("C:/Users/Umberto/Desktop/Challenge-city/GNN_Colab_Training.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)
